layout: {dts_layout: boards/shields/hookah/hookah-layouts.dtsi, layout_name: hookah_layout}
layers:
  Default:
  - ''
  - ''
  - W
  - F
  - P
  - B
  - J
  - L
  - U
  - Y
  - ''
  - ''
  - Q
  - {t: A, h: LGUI}
  - {t: R, h: LALT}
  - {t: S, h: LCTRL}
  - {t: T, h: LSHFT}
  - G
  - M
  - {t: N, h: RSHFT}
  - {t: E, h: LCTRL}
  - {t: I, h: LALT}
  - {t: O, h: RGUI}
  - ''''
  - ''
  - Z
  - X
  - C
  - D
  - V
  - K
  - H
  - ','
  - .
  - /
  - ''
  - ''
  - ''
  - {t: ESC, h: Nav}
  - {t: SPACE, h: Mou Key}
  - {t: RET, h: Sym}
  - {t: BKSP, h: Num}
  - ''
  - ''
  Num:
  - ''
  - ''
  - '7'
  - '8'
  - '9'
  - ']'
  - ''
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '['
  - ;
  - '4'
  - '5'
  - '6'
  - '='
  - ''
  - TAB
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ESC
  - {t: ▽, type: trans}
  - ''
  - '`'
  - '1'
  - '2'
  - '3'
  - \
  - ''
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ''
  - {t: ▽, type: trans}
  - '0'
  - '-'
  - ''
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  Sym:
  - ''
  - ''
  - '&'
  - '*'
  - (
  - '}'
  - ''
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '{'
  - ':'
  - $
  - '%'
  - ^
  - +
  - ''
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ''
  - '~'
  - '!'
  - '@'
  - '#'
  - '|'
  - ''
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ''
  - {t: ▽, type: trans}
  - )
  - _
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  Nav:
  - ''
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ''
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ''
  - ''
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - LEFT
  - DOWN
  - UP
  - RIGHT
  - CAPSLOCK
  - ''
  - ''
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - HOME
  - PG DN
  - PG UP
  - END
  - INS
  - ''
  - ''
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - ''
  - ''
  - ''
  - ''
  Mou Key:
  - ''
  - F1
  - F2
  - F3
  - {t: F4, h: Mou Scroll}
  - F5
  - F6
  - {t: F7, h: Mou Scroll}
  - F8
  - F9
  - F10
  - ''
  - F1
  - VOL DN
  - VOL UP
  - BRI DN
  - BRI UP
  - F12
  - '&m_v (0)'
  - '&m_v (0)'
  - '&m_v (0)'
  - '&m_v (0)'
  - F11
  - F10
  - ''
  - Mou Scroll
  - '&mkp RCLK'
  - '&mkp MCLK'
  - '&mkp LCLK'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '&mkp LCLK'
  - '&mkp MCLK'
  - '&mkp RCLK'
  - Mou Scroll
  - ''
  - ''
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ''
  Mou Scroll:
  - ''
  - ''
  - {t: BT, h: '0'}
  - {t: BT, h: '1'}
  - {t: BT CLR, type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - A
  - '&bootloader'
  - ''
  - ''
  - '&sys_reset'
  - ''
  - ''
  - ''
  - '&studio_unlock'
  - '&m_v (0)'
  - '&m_v (0)'
  - '&m_v (0)'
  - '&m_v (0)'
  - '&sys_reset'
  - '&bootloader'
  - ''
  - {t: ▽, type: trans}
  - '&mkp RCLK'
  - '&mkp MCLK'
  - '&mkp LCLK'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '&mkp LCLK'
  - '&mkp MCLK'
  - '&mkp RCLK'
  - {t: ▽, type: trans}
  - ''
  - ''
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ''
