manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # For ZMK dongle with OLED.
    - name: englmaxi
      url-base: https://github.com/englmaxi
    - name: infused-kim
      url-base: https://github.com/infused-kim
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      # remote: zmkfirmware
      # revision: main
      # remote: infused-kim
      # revision: pr-testing/mouse_ps2_module_base
      remote: badjeff
      revision: main
      import: app/west.yml
    - name: zmk-dongle-display
      remote: englmaxi
      revision: main
    # Module for PS/2 mouse & TP driver
    - name: kb_zmk_ps2_mouse_trackpoint_driver
      remote: infused-kim
      revision: main

  self:
    path: config
