manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # For ZMK dongle with OLED.
    - name: englmaxi
      url-base: https://github.com/englmaxi
    - name: infused-kim
      url-base: https://github.com/infused-kim
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      # remote: badjeff
      # revision: feat/pointers-with-input-processors
      import: app/west.yml
    - name: zmk-dongle-display
      remote: englmaxi
      revision: main
    # - name: zmk-split-peripheral-input-relay
      # remote: badjeff
      # revision: main
    - name: kb_zmk_ps2_mouse_trackpoint_driver
      remote: badjeff
      revision: main

  self:
    path: config